# Generated by Django 4.0.5 on 2022-07-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('nombre_gerente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('anio_fabricacion', models.IntegerField()),
                ('valor_fijo_venta', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tipo', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Deportiva', 'Deportiva')], max_length=30)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasmotos', to='ventas.concesionario')),
            ],
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('anio_fabricacion', models.IntegerField()),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=100)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=100)),
                ('color', models.CharField(max_length=30)),
                ('valor_alarma', models.DecimalField(decimal_places=2, max_digits=100)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losvehiculos', to='ventas.concesionario')),
            ],
        ),
    ]
